spring:
  application:
    name: gateway
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://keycloak:8181/realms/spring-boot-realm-dev
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/users/**
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/cards/**
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/accounts/**
        - id: registrationUserService
          uri: lb://registrationUserService
          predicates:
            - Path=/registration/**
server:
  port: 8080
