spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-boot-realm-dev
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Red, Blue
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products
            
server:
  port: 8084
